# Generated by Django 2.1 on 2019-01-14 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_eventdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdetails',
            name='event_date',
            field=models.DateTimeField(verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='eventdetails',
            name='last_date',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
