# Generated by Django 2.1 on 2019-01-14 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190115_0215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdetails',
            name='event_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='eventdetails',
            name='last_date',
            field=models.DateField(),
        ),
    ]
