# Generated by Django 2.1 on 2019-01-14 21:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20190115_0235'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdetails',
            name='last_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 14, 21, 5, 38, 890827, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='eventdetails',
            name='event_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 14, 21, 5, 38, 890791, tzinfo=utc)),
        ),
    ]
