# Generated by Django 2.1 on 2019-01-14 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20190115_0235'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventDetails',
        ),
    ]
