# Generated by Django 2.1 on 2019-01-15 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_delete_eventdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='year',
        ),
        migrations.AddField(
            model_name='customuser',
            name='contact_no',
            field=models.IntegerField(default=1234567890, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='roll',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
