# Generated by Django 2.1 on 2019-01-14 23:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('venue', models.CharField(max_length=200)),
                ('event_date', models.DateTimeField(default=datetime.datetime(2019, 1, 14, 23, 37, 58, 117980, tzinfo=utc))),
                ('fee', models.FloatField(default=0)),
                ('last_date', models.DateTimeField(default=datetime.datetime(2019, 1, 14, 23, 37, 58, 118019, tzinfo=utc))),
            ],
        ),
    ]
