# Generated by Django 2.1 on 2019-01-15 04:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestedEvents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('feasible_event_date', models.DateTimeField(default=datetime.datetime(2019, 1, 15, 4, 29, 25, 799872, tzinfo=utc))),
            ],
        ),
        migrations.AlterField(
            model_name='eventdetails',
            name='event_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 15, 4, 29, 25, 799400, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='eventdetails',
            name='last_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 15, 4, 29, 25, 799440, tzinfo=utc)),
        ),
    ]
