# Generated by Django 2.1 on 2019-01-15 06:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_auto_20190115_0959'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registrants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='eventdetails',
            name='event_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 15, 6, 36, 11, 799158, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='eventdetails',
            name='last_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 15, 6, 36, 11, 799197, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='suggestedevents',
            name='feasible_event_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 15, 6, 36, 11, 799728, tzinfo=utc)),
        ),
    ]
