# Generated by Django 2.1 on 2019-01-15 07:08

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0003_auto_20190115_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrants',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.EventDetails'),
        ),
        migrations.AlterField(
            model_name='eventdetails',
            name='event_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 15, 7, 8, 50, 641884, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='eventdetails',
            name='last_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 15, 7, 8, 50, 641923, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='suggestedevents',
            name='feasible_event_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 15, 7, 8, 50, 642432, tzinfo=utc)),
        ),
    ]
