# Generated by Django 2.1 on 2019-01-15 13:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0004_auto_20190115_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdetails',
            name='event_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 15, 13, 30, 51, 307300, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='eventdetails',
            name='last_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 15, 13, 30, 51, 307339, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='suggestedevents',
            name='feasible_event_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 15, 13, 30, 51, 307911, tzinfo=utc)),
        ),
    ]
