# Generated by Django 2.1 on 2019-01-15 14:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0005_auto_20190115_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdetails',
            name='event_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 15, 14, 4, 25, 385031, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='eventdetails',
            name='last_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 15, 14, 4, 25, 385068, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='suggestedevents',
            name='feasible_event_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 15, 14, 4, 25, 385456, tzinfo=utc)),
        ),
    ]
